version: "3"

services:
  postgres:
    image: postgres
    container_name: job-market-analysis-db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: job-analysis
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
