version: "3"

services:
  postgres:
    image: postgres
    container_name: job-market-analysis-db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
